import { OpportunitiesService } from './opportunities.service';
import { CreateOpportunityDto } from './dto/create-opportunity.dto';
import { SetBidOwnersDto } from './dto/set-bid-owners.dto';
import { UpdateOpportunityDto } from './dto/update-opportunity.dto';
import { QueryOpportunityDto } from './dto/query-opportunity.dto';
import { UpdateChecklistDto } from './dto/update-checklist.dto';
import { TenantService } from '../../tenant/tenant.service';
export declare class OpportunitiesController {
    private readonly service;
    private tenants;
    constructor(service: OpportunitiesService, tenants: TenantService);
    list(query: QueryOpportunityDto, req: any): Promise<{
        items: {
            clientName: string;
            bidOwners: {
                id: string;
                name: string;
                email: string;
            }[];
            daysLeft: number | null;
            startDate: Date | null;
            clientId: string;
            title: string;
            description: string | null;
            tenderRef: string | null;
            boqTemplateId: string | null;
            packTemplateId: string | null;
            ownerId: string | null;
            submissionDate: Date | null;
            status: string | null;
            stage: string | null;
            priorityRank: number | null;
            modeOfSubmission: string | null;
            sourcePortal: string | null;
            bondRequired: boolean | null;
            validityDays: number | null;
            dataOwner: string | null;
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            sourceTenderId: string | null;
            discoveryDate: Date | null;
            bondAmount: number | null;
            goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
            goNoGoUpdatedAt: Date | null;
            bondReminderSentAt: Date | null;
            reviewFreezeReminderSentAt: Date | null;
            portalRehearsalReminderSentAt: Date | null;
            slaLastNotifiedLevel: string | null;
            slaLastNotifiedAt: Date | null;
        }[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    create(body: CreateOpportunityDto, req: any): Promise<{
        client: {
            id: string;
            name: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            sector: string | null;
        };
        owner: {
            status: import("@prisma/client").$Enums.UserStatus;
            id: string;
            email: string;
            name: string;
            role: import("@prisma/client").$Enums.Role;
            team: string | null;
            passwordHash: string | null;
            isActive: boolean;
            mustChangePassword: boolean;
            lastLoginAt: Date | null;
            passwordChangedAt: Date | null;
            userType: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    } & {
        clientId: string;
        title: string;
        description: string | null;
        tenderRef: string | null;
        boqTemplateId: string | null;
        packTemplateId: string | null;
        ownerId: string | null;
        submissionDate: Date | null;
        status: string | null;
        stage: string | null;
        priorityRank: number | null;
        daysLeft: number | null;
        modeOfSubmission: string | null;
        sourcePortal: string | null;
        bondRequired: boolean | null;
        validityDays: number | null;
        dataOwner: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        sourceTenderId: string | null;
        discoveryDate: Date | null;
        startDate: Date | null;
        bondAmount: number | null;
        goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
        goNoGoUpdatedAt: Date | null;
        bondReminderSentAt: Date | null;
        reviewFreezeReminderSentAt: Date | null;
        portalRehearsalReminderSentAt: Date | null;
        slaLastNotifiedLevel: string | null;
        slaLastNotifiedAt: Date | null;
    }>;
    update(id: string, body: UpdateOpportunityDto, req: any): Promise<{
        clientId: string;
        title: string;
        description: string | null;
        tenderRef: string | null;
        boqTemplateId: string | null;
        packTemplateId: string | null;
        ownerId: string | null;
        submissionDate: Date | null;
        status: string | null;
        stage: string | null;
        priorityRank: number | null;
        daysLeft: number | null;
        modeOfSubmission: string | null;
        sourcePortal: string | null;
        bondRequired: boolean | null;
        validityDays: number | null;
        dataOwner: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        sourceTenderId: string | null;
        discoveryDate: Date | null;
        startDate: Date | null;
        bondAmount: number | null;
        goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
        goNoGoUpdatedAt: Date | null;
        bondReminderSentAt: Date | null;
        reviewFreezeReminderSentAt: Date | null;
        portalRehearsalReminderSentAt: Date | null;
        slaLastNotifiedLevel: string | null;
        slaLastNotifiedAt: Date | null;
    }>;
    setBidOwners(id: string, body: SetBidOwnersDto, req: any): Promise<{
        userIds: string[];
    }>;
    remove(id: string, req: any): Promise<{
        clientId: string;
        title: string;
        description: string | null;
        tenderRef: string | null;
        boqTemplateId: string | null;
        packTemplateId: string | null;
        ownerId: string | null;
        submissionDate: Date | null;
        status: string | null;
        stage: string | null;
        priorityRank: number | null;
        daysLeft: number | null;
        modeOfSubmission: string | null;
        sourcePortal: string | null;
        bondRequired: boolean | null;
        validityDays: number | null;
        dataOwner: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        sourceTenderId: string | null;
        discoveryDate: Date | null;
        startDate: Date | null;
        bondAmount: number | null;
        goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
        goNoGoUpdatedAt: Date | null;
        bondReminderSentAt: Date | null;
        reviewFreezeReminderSentAt: Date | null;
        portalRehearsalReminderSentAt: Date | null;
        slaLastNotifiedLevel: string | null;
        slaLastNotifiedAt: Date | null;
    }>;
    getChecklist(id: string, req: any): Promise<{
        notes: import("@prisma/client/runtime/library").JsonValue | null;
        bondPurchased: boolean;
        formsCompleted: boolean;
        finalPdfReady: boolean;
        portalCredentialsVerified: boolean;
        complianceCreated: boolean;
        clarificationsSent: boolean;
        pricingApproved: boolean;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        bondPurchasedAt: Date | null;
        bondPurchasedById: string | null;
        bondPurchaseAttachmentId: string | null;
        formsCompletedAt: Date | null;
        formsCompletedById: string | null;
        formsAttachmentId: string | null;
        finalPdfReadyAt: Date | null;
        finalPdfReadyById: string | null;
        finalPdfAttachmentId: string | null;
        portalCredentialsVerifiedAt: Date | null;
        portalCredentialsVerifiedById: string | null;
        portalCredentialsAttachmentId: string | null;
        complianceCreatedAt: Date | null;
        complianceCreatedById: string | null;
        complianceCreatedAttachmentId: string | null;
        clarificationsSentAt: Date | null;
        clarificationsSentById: string | null;
        clarificationsSentAttachmentId: string | null;
        pricingApprovedAt: Date | null;
        pricingApprovedById: string | null;
    }>;
    updateChecklist(id: string, body: UpdateChecklistDto, req: any): Promise<{
        notes: import("@prisma/client/runtime/library").JsonValue | null;
        bondPurchased: boolean;
        formsCompleted: boolean;
        finalPdfReady: boolean;
        portalCredentialsVerified: boolean;
        complianceCreated: boolean;
        clarificationsSent: boolean;
        pricingApproved: boolean;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        bondPurchasedAt: Date | null;
        bondPurchasedById: string | null;
        bondPurchaseAttachmentId: string | null;
        formsCompletedAt: Date | null;
        formsCompletedById: string | null;
        formsAttachmentId: string | null;
        finalPdfReadyAt: Date | null;
        finalPdfReadyById: string | null;
        finalPdfAttachmentId: string | null;
        portalCredentialsVerifiedAt: Date | null;
        portalCredentialsVerifiedById: string | null;
        portalCredentialsAttachmentId: string | null;
        complianceCreatedAt: Date | null;
        complianceCreatedById: string | null;
        complianceCreatedAttachmentId: string | null;
        clarificationsSentAt: Date | null;
        clarificationsSentById: string | null;
        clarificationsSentAttachmentId: string | null;
        pricingApprovedAt: Date | null;
        pricingApprovedById: string | null;
    }>;
    get(id: string, req: any): Promise<{
        clientName: string;
        bidOwners: {
            id: string;
            name: string;
            email: string;
        }[];
        daysLeft: number | null;
        clientId: string;
        title: string;
        description: string | null;
        tenderRef: string | null;
        boqTemplateId: string | null;
        packTemplateId: string | null;
        ownerId: string | null;
        submissionDate: Date | null;
        status: string | null;
        stage: string | null;
        priorityRank: number | null;
        modeOfSubmission: string | null;
        sourcePortal: string | null;
        bondRequired: boolean | null;
        validityDays: number | null;
        dataOwner: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        sourceTenderId: string | null;
        discoveryDate: Date | null;
        startDate: Date | null;
        bondAmount: number | null;
        goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
        goNoGoUpdatedAt: Date | null;
        bondReminderSentAt: Date | null;
        reviewFreezeReminderSentAt: Date | null;
        portalRehearsalReminderSentAt: Date | null;
        slaLastNotifiedLevel: string | null;
        slaLastNotifiedAt: Date | null;
    } | null>;
}
