import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
export declare class TendersService {
    private prisma;
    constructor(prisma: PrismaService);
    list(filters: {
        q?: string;
        portal?: string;
        status?: string;
        scope?: string;
        scopes?: string;
        minScore?: number;
        isNew?: string;
        promoted?: string;
        goNoGoStatus?: string;
        fromDate?: string;
        toDate?: string;
        page?: number;
        pageSize?: number;
    }, tenantId: string): Promise<{
        items: ({
            classification: {
                id: string;
                tenantId: string;
                createdAt: Date;
                updatedAt: Date;
                isNew: boolean;
                tenderId: string;
                classificationVersion: number;
                score: number;
                matchedActivityIds: string[];
                matchedScopes: import("@prisma/client").$Enums.TenderScope[];
                matchedKeywords: string[];
                reasons: string[];
            } | null;
        } & {
            title: string | null;
            tenderRef: string | null;
            status: string | null;
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            portal: string;
            titleOriginal: string | null;
            ministry: string | null;
            publishDate: Date | null;
            closeDate: Date | null;
            requestedSectorType: string | null;
            tenderBondValue: number | null;
            documentsValue: number | null;
            tenderType: string | null;
            purchaseUrl: string | null;
            sourceUrl: string | null;
        })[];
        total: number;
        page: number;
        pageSize: number;
    }>;
    get(id: string): Prisma.Prisma__MinistryTenderClient<({
        classification: {
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            isNew: boolean;
            tenderId: string;
            classificationVersion: number;
            score: number;
            matchedActivityIds: string[];
            matchedScopes: import("@prisma/client").$Enums.TenderScope[];
            matchedKeywords: string[];
            reasons: string[];
        } | null;
    } & {
        title: string | null;
        tenderRef: string | null;
        status: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        portal: string;
        titleOriginal: string | null;
        ministry: string | null;
        publishDate: Date | null;
        closeDate: Date | null;
        requestedSectorType: string | null;
        tenderBondValue: number | null;
        documentsValue: number | null;
        tenderType: string | null;
        purchaseUrl: string | null;
        sourceUrl: string | null;
    }) | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    create(data: any, tenantId: string): Promise<{
        title: string | null;
        tenderRef: string | null;
        status: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        portal: string;
        titleOriginal: string | null;
        ministry: string | null;
        publishDate: Date | null;
        closeDate: Date | null;
        requestedSectorType: string | null;
        tenderBondValue: number | null;
        documentsValue: number | null;
        tenderType: string | null;
        purchaseUrl: string | null;
        sourceUrl: string | null;
    }>;
    update(id: string, data: any): Promise<{
        title: string | null;
        tenderRef: string | null;
        status: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        portal: string;
        titleOriginal: string | null;
        ministry: string | null;
        publishDate: Date | null;
        closeDate: Date | null;
        requestedSectorType: string | null;
        tenderBondValue: number | null;
        documentsValue: number | null;
        tenderType: string | null;
        purchaseUrl: string | null;
        sourceUrl: string | null;
    }>;
    remove(id: string): Prisma.Prisma__MinistryTenderClient<{
        title: string | null;
        tenderRef: string | null;
        status: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        portal: string;
        titleOriginal: string | null;
        ministry: string | null;
        publishDate: Date | null;
        closeDate: Date | null;
        requestedSectorType: string | null;
        tenderBondValue: number | null;
        documentsValue: number | null;
        tenderType: string | null;
        purchaseUrl: string | null;
        sourceUrl: string | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    promoteToOpportunity(id: string, tenantId: string): Promise<{
        clientId: string;
        title: string;
        description: string | null;
        tenderRef: string | null;
        boqTemplateId: string | null;
        packTemplateId: string | null;
        ownerId: string | null;
        submissionDate: Date | null;
        status: string | null;
        stage: string | null;
        priorityRank: number | null;
        daysLeft: number | null;
        modeOfSubmission: string | null;
        sourcePortal: string | null;
        bondRequired: boolean | null;
        validityDays: number | null;
        dataOwner: string | null;
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        sourceTenderId: string | null;
        discoveryDate: Date | null;
        startDate: Date | null;
        bondAmount: number | null;
        goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
        goNoGoUpdatedAt: Date | null;
        bondReminderSentAt: Date | null;
        reviewFreezeReminderSentAt: Date | null;
        portalRehearsalReminderSentAt: Date | null;
        slaLastNotifiedLevel: string | null;
        slaLastNotifiedAt: Date | null;
    }>;
    triggerCollector(payload: {
        adapterId?: string;
        fromDate?: string;
        toDate?: string;
    }): Promise<{
        jobId: string | undefined;
        status: string;
    }>;
    listActivities(tenantId: string): Prisma.PrismaPromise<{
        description: string | null;
        id: string;
        name: string;
        isActive: boolean;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        scope: import("@prisma/client").$Enums.TenderScope;
        keywords: string[];
        negativeKeywords: string[];
        weight: number | null;
        isHighPriority: boolean;
    }[]>;
    createActivity(data: any, tenantId: string): Promise<{
        description: string | null;
        id: string;
        name: string;
        isActive: boolean;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        scope: import("@prisma/client").$Enums.TenderScope;
        keywords: string[];
        negativeKeywords: string[];
        weight: number | null;
        isHighPriority: boolean;
    }>;
    updateActivity(id: string, data: any, tenantId: string): Promise<{
        description: string | null;
        id: string;
        name: string;
        isActive: boolean;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        scope: import("@prisma/client").$Enums.TenderScope;
        keywords: string[];
        negativeKeywords: string[];
        weight: number | null;
        isHighPriority: boolean;
    } | null>;
    getClassification(tenderId: string, tenantId: string): Promise<{
        matchedActivities: ({
            description: string | null;
            id: string;
            name: string;
            isActive: boolean;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            scope: import("@prisma/client").$Enums.TenderScope;
            keywords: string[];
            negativeKeywords: string[];
            weight: number | null;
            isHighPriority: boolean;
        } | undefined)[];
        id: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        isNew: boolean;
        tenderId: string;
        classificationVersion: number;
        score: number;
        matchedActivityIds: string[];
        matchedScopes: import("@prisma/client").$Enums.TenderScope[];
        matchedKeywords: string[];
        reasons: string[];
    } | null>;
    reprocessClassifications(payload: {
        fromDate?: string;
        toDate?: string;
        portal?: string;
    }, tenantId: string, userId?: string): Promise<{
        processed: number;
        errors: number;
        runId: string;
    }>;
    translateExistingTitles(payload: {
        portal?: string;
        fromDate?: string;
        toDate?: string;
        limit?: number;
        dryRun?: boolean | string;
    }, tenantId: string, triggeredBy?: string): Promise<{
        limit: number;
        dryRun: boolean;
        portal: string | null;
        triggeredBy: string | null;
        scanned: number;
        translated: number;
        skipped: number;
        failed: number;
        errors: Array<{
            tenderId: string;
            message: string;
        }>;
    }>;
    private parseBoolean;
    private parseNumber;
    private normalizeTenderTitle;
    private normalizeScope;
    private parseStringArray;
    private loadSmartFilterConfig;
    private upsertClassification;
}
