import { PrismaService } from '../../prisma/prisma.service';
export declare class PricingService {
    private prisma;
    constructor(prisma: PrismaService);
    listBoq(opportunityId: string): import("@prisma/client").Prisma.PrismaPromise<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        category: string | null;
        qty: number;
        unit: string | null;
        oem: string | null;
        sku: string | null;
        unitCost: number;
        unitCurrency: string;
        markup: number;
        unitPrice: number;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }[]>;
    createBoq(opportunityId: string, data: any): import("@prisma/client").Prisma.Prisma__BoQItemClient<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        category: string | null;
        qty: number;
        unit: string | null;
        oem: string | null;
        sku: string | null;
        unitCost: number;
        unitCurrency: string;
        markup: number;
        unitPrice: number;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    updateBoq(id: string, data: any): import("@prisma/client").Prisma.Prisma__BoQItemClient<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        category: string | null;
        qty: number;
        unit: string | null;
        oem: string | null;
        sku: string | null;
        unitCost: number;
        unitCurrency: string;
        markup: number;
        unitPrice: number;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    deleteBoq(id: string): import("@prisma/client").Prisma.Prisma__BoQItemClient<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        category: string | null;
        qty: number;
        unit: string | null;
        oem: string | null;
        sku: string | null;
        unitCost: number;
        unitCurrency: string;
        markup: number;
        unitPrice: number;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    listQuotes(opportunityId: string): import("@prisma/client").Prisma.PrismaPromise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        currency: string | null;
        vendor: string;
        quoteNo: string | null;
        validity: Date | null;
        leadTimeDays: number | null;
        files: string | null;
    }[]>;
    listPackRows(opportunityId: string): import("@prisma/client").Prisma.PrismaPromise<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        qty: number;
        unit: string | null;
        unitCost: number;
        unitCurrency: string;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }[]>;
    createPackRow(opportunityId: string, data: any): import("@prisma/client").Prisma.Prisma__PricingPackRowClient<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        qty: number;
        unit: string | null;
        unitCost: number;
        unitCurrency: string;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    updatePackRow(id: string, data: any): import("@prisma/client").Prisma.Prisma__PricingPackRowClient<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        qty: number;
        unit: string | null;
        unitCost: number;
        unitCurrency: string;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    deletePackRow(id: string): import("@prisma/client").Prisma.Prisma__PricingPackRowClient<{
        description: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        lineNo: number;
        qty: number;
        unit: string | null;
        unitCost: number;
        unitCurrency: string;
        customFields: import("@prisma/client/runtime/library").JsonValue | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    listTemplates(tenantId: string, workspace?: string, opportunityId?: string): import("@prisma/client").Prisma.PrismaPromise<{
        id: string;
        name: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string | null;
        workspace: import("@prisma/client").$Enums.PricingWorkspace;
        scope: import("@prisma/client").$Enums.PricingTemplateScope;
        columns: import("@prisma/client/runtime/library").JsonValue;
    }[]>;
    createTemplate(tenantId: string, data: any): import("@prisma/client").Prisma.Prisma__PricingTemplateClient<{
        id: string;
        name: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string | null;
        workspace: import("@prisma/client").$Enums.PricingWorkspace;
        scope: import("@prisma/client").$Enums.PricingTemplateScope;
        columns: import("@prisma/client/runtime/library").JsonValue;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    updateTemplate(id: string, data: any): import("@prisma/client").Prisma.Prisma__PricingTemplateClient<{
        id: string;
        name: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string | null;
        workspace: import("@prisma/client").$Enums.PricingWorkspace;
        scope: import("@prisma/client").$Enums.PricingTemplateScope;
        columns: import("@prisma/client/runtime/library").JsonValue;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    deleteTemplate(id: string): import("@prisma/client").Prisma.Prisma__PricingTemplateClient<{
        id: string;
        name: string;
        tenantId: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string | null;
        workspace: import("@prisma/client").$Enums.PricingWorkspace;
        scope: import("@prisma/client").$Enums.PricingTemplateScope;
        columns: import("@prisma/client/runtime/library").JsonValue;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    createQuote(opportunityId: string, data: any): import("@prisma/client").Prisma.Prisma__VendorQuoteClient<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        currency: string | null;
        vendor: string;
        quoteNo: string | null;
        validity: Date | null;
        leadTimeDays: number | null;
        files: string | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    updateQuote(id: string, data: any): import("@prisma/client").Prisma.Prisma__VendorQuoteClient<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        opportunityId: string;
        currency: string | null;
        vendor: string;
        quoteNo: string | null;
        validity: Date | null;
        leadTimeDays: number | null;
        files: string | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs>;
    recalcPack(opportunityId: string, tenantId: string, overrides?: Partial<{
        overheads: number;
        contingency: number;
        fxRate: number;
        margin: number;
    }>): Promise<{
        pack: {
            fxRate: number;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            opportunityId: string;
            version: number;
            baseCost: number;
            overheads: number;
            contingency: number;
            margin: number;
            totalPrice: number;
        };
        baseCost: number;
        totalPrice: number;
    }>;
}
