import { Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { ApprovalType } from '@prisma/client';
import { RequestWorkApprovalDto } from './dto/request-work-approval.dto';
import { ApprovalDecisionDto } from './dto/approval-decision.dto';
import { NotificationsService } from '../notifications/notifications.service';
import { RejectWorkApprovalDto } from './dto/reject-work-approval.dto';
interface UserContext {
    id?: string;
    role?: string;
    tenantId?: string;
}
export declare class ApprovalsService {
    private prisma;
    private notifications;
    constructor(prisma: PrismaService, notifications: NotificationsService);
    list(packId: string): Prisma.PrismaPromise<{
        status: import("@prisma/client").$Enums.ApprovalStatus;
        stage: import("@prisma/client").$Enums.ApprovalStage;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        type: import("@prisma/client").$Enums.ApprovalType;
        sourceTenderId: string | null;
        attachments: Prisma.JsonValue | null;
        comment: string | null;
        changesRequestedDueDate: Date | null;
        packId: string;
        approverRole: string | null;
        approverIds: string[];
        approverId: string | null;
        requestedAt: Date | null;
        decidedAt: Date | null;
        reworkCount: number;
        lateDecision: boolean;
        signedOn: Date | null;
        signature: string | null;
        remarks: string | null;
    }[]>;
    reviewOverview(tenantId: string, user?: UserContext, scope?: 'mine' | 'all'): Promise<any[]>;
    private enrichPack;
    requestWorkApproval(dto: RequestWorkApprovalDto, user: UserContext): Promise<{
        opportunity: {
            clientId: string;
            title: string;
            description: string | null;
            tenderRef: string | null;
            boqTemplateId: string | null;
            packTemplateId: string | null;
            ownerId: string | null;
            submissionDate: Date | null;
            status: string | null;
            stage: string | null;
            priorityRank: number | null;
            daysLeft: number | null;
            modeOfSubmission: string | null;
            sourcePortal: string | null;
            bondRequired: boolean | null;
            validityDays: number | null;
            dataOwner: string | null;
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            sourceTenderId: string | null;
            discoveryDate: Date | null;
            startDate: Date | null;
            bondAmount: number | null;
            goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
            goNoGoUpdatedAt: Date | null;
            bondReminderSentAt: Date | null;
            reviewFreezeReminderSentAt: Date | null;
            portalRehearsalReminderSentAt: Date | null;
            slaLastNotifiedLevel: string | null;
            slaLastNotifiedAt: Date | null;
        };
        packId: string;
        approvalId: string;
    }>;
    rejectWorkApproval(dto: RejectWorkApprovalDto, user: UserContext): Promise<{
        opportunity: {
            clientId: string;
            title: string;
            description: string | null;
            tenderRef: string | null;
            boqTemplateId: string | null;
            packTemplateId: string | null;
            ownerId: string | null;
            submissionDate: Date | null;
            status: string | null;
            stage: string | null;
            priorityRank: number | null;
            daysLeft: number | null;
            modeOfSubmission: string | null;
            sourcePortal: string | null;
            bondRequired: boolean | null;
            validityDays: number | null;
            dataOwner: string | null;
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            sourceTenderId: string | null;
            discoveryDate: Date | null;
            startDate: Date | null;
            bondAmount: number | null;
            goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
            goNoGoUpdatedAt: Date | null;
            bondReminderSentAt: Date | null;
            reviewFreezeReminderSentAt: Date | null;
            portalRehearsalReminderSentAt: Date | null;
            slaLastNotifiedLevel: string | null;
            slaLastNotifiedAt: Date | null;
        };
        packId: string;
        approvalId: string;
    }>;
    bootstrap(packId: string, chain?: {
        role?: string;
        userId?: string;
        type: ApprovalType;
        stage?: string;
    }[]): Promise<{
        status: import("@prisma/client").$Enums.ApprovalStatus;
        stage: import("@prisma/client").$Enums.ApprovalStage;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        type: import("@prisma/client").$Enums.ApprovalType;
        sourceTenderId: string | null;
        attachments: Prisma.JsonValue | null;
        comment: string | null;
        changesRequestedDueDate: Date | null;
        packId: string;
        approverRole: string | null;
        approverIds: string[];
        approverId: string | null;
        requestedAt: Date | null;
        decidedAt: Date | null;
        reworkCount: number;
        lateDecision: boolean;
        signedOn: Date | null;
        signature: string | null;
        remarks: string | null;
    }[]>;
    finalize(packId: string, tenantId: string, userId?: string): Promise<{
        packId: string;
    }>;
    private markPricingApproved;
    decision(id: string, userId: string, userRole: string, body: ApprovalDecisionDto): Promise<{
        status: import("@prisma/client").$Enums.ApprovalStatus;
        stage: import("@prisma/client").$Enums.ApprovalStage;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        type: import("@prisma/client").$Enums.ApprovalType;
        sourceTenderId: string | null;
        attachments: Prisma.JsonValue | null;
        comment: string | null;
        changesRequestedDueDate: Date | null;
        packId: string;
        approverRole: string | null;
        approverIds: string[];
        approverId: string | null;
        requestedAt: Date | null;
        decidedAt: Date | null;
        reworkCount: number;
        lateDecision: boolean;
        signedOn: Date | null;
        signature: string | null;
        remarks: string | null;
    }>;
}
export {};
