import { TenantService } from '../../tenant/tenant.service';
import { ApprovalsService } from './approvals.service';
import { RequestWorkApprovalDto } from './dto/request-work-approval.dto';
import { ApprovalDecisionDto } from './dto/approval-decision.dto';
import { RejectWorkApprovalDto } from './dto/reject-work-approval.dto';
declare class ReviewApprovalsQuery {
    scope?: 'mine' | 'all';
}
export declare class ApprovalsController {
    private svc;
    private tenants;
    constructor(svc: ApprovalsService, tenants: TenantService);
    review(query: ReviewApprovalsQuery, req: any): Promise<any[]>;
    list(packId: string, req: any): Promise<{
        status: import("@prisma/client").$Enums.ApprovalStatus;
        stage: import("@prisma/client").$Enums.ApprovalStage;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        type: import("@prisma/client").$Enums.ApprovalType;
        sourceTenderId: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        comment: string | null;
        changesRequestedDueDate: Date | null;
        packId: string;
        approverRole: string | null;
        approverIds: string[];
        approverId: string | null;
        requestedAt: Date | null;
        decidedAt: Date | null;
        reworkCount: number;
        lateDecision: boolean;
        signedOn: Date | null;
        signature: string | null;
        remarks: string | null;
    }[]>;
    request(body: RequestWorkApprovalDto, req: any): Promise<{
        opportunity: {
            clientId: string;
            title: string;
            description: string | null;
            tenderRef: string | null;
            boqTemplateId: string | null;
            packTemplateId: string | null;
            ownerId: string | null;
            submissionDate: Date | null;
            status: string | null;
            stage: string | null;
            priorityRank: number | null;
            daysLeft: number | null;
            modeOfSubmission: string | null;
            sourcePortal: string | null;
            bondRequired: boolean | null;
            validityDays: number | null;
            dataOwner: string | null;
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            sourceTenderId: string | null;
            discoveryDate: Date | null;
            startDate: Date | null;
            bondAmount: number | null;
            goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
            goNoGoUpdatedAt: Date | null;
            bondReminderSentAt: Date | null;
            reviewFreezeReminderSentAt: Date | null;
            portalRehearsalReminderSentAt: Date | null;
            slaLastNotifiedLevel: string | null;
            slaLastNotifiedAt: Date | null;
        };
        packId: string;
        approvalId: string;
    }>;
    reject(body: RejectWorkApprovalDto, req: any): Promise<{
        opportunity: {
            clientId: string;
            title: string;
            description: string | null;
            tenderRef: string | null;
            boqTemplateId: string | null;
            packTemplateId: string | null;
            ownerId: string | null;
            submissionDate: Date | null;
            status: string | null;
            stage: string | null;
            priorityRank: number | null;
            daysLeft: number | null;
            modeOfSubmission: string | null;
            sourcePortal: string | null;
            bondRequired: boolean | null;
            validityDays: number | null;
            dataOwner: string | null;
            id: string;
            tenantId: string;
            createdAt: Date;
            updatedAt: Date;
            sourceTenderId: string | null;
            discoveryDate: Date | null;
            startDate: Date | null;
            bondAmount: number | null;
            goNoGoStatus: import("@prisma/client").$Enums.ApprovalStatus;
            goNoGoUpdatedAt: Date | null;
            bondReminderSentAt: Date | null;
            reviewFreezeReminderSentAt: Date | null;
            portalRehearsalReminderSentAt: Date | null;
            slaLastNotifiedLevel: string | null;
            slaLastNotifiedAt: Date | null;
        };
        packId: string;
        approvalId: string;
    }>;
    bootstrap(packId: string, body: any, req: any): Promise<{
        status: import("@prisma/client").$Enums.ApprovalStatus;
        stage: import("@prisma/client").$Enums.ApprovalStage;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        type: import("@prisma/client").$Enums.ApprovalType;
        sourceTenderId: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        comment: string | null;
        changesRequestedDueDate: Date | null;
        packId: string;
        approverRole: string | null;
        approverIds: string[];
        approverId: string | null;
        requestedAt: Date | null;
        decidedAt: Date | null;
        reworkCount: number;
        lateDecision: boolean;
        signedOn: Date | null;
        signature: string | null;
        remarks: string | null;
    }[]>;
    decision(id: string, body: ApprovalDecisionDto, req: any): Promise<{
        status: import("@prisma/client").$Enums.ApprovalStatus;
        stage: import("@prisma/client").$Enums.ApprovalStage;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        type: import("@prisma/client").$Enums.ApprovalType;
        sourceTenderId: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        comment: string | null;
        changesRequestedDueDate: Date | null;
        packId: string;
        approverRole: string | null;
        approverIds: string[];
        approverId: string | null;
        requestedAt: Date | null;
        decidedAt: Date | null;
        reworkCount: number;
        lateDecision: boolean;
        signedOn: Date | null;
        signature: string | null;
        remarks: string | null;
    }>;
    finalize(packId: string, req: any): Promise<{
        packId: string;
    }>;
}
export {};
